[project]
name = 'balanced-clarity-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.asset-manager]
path = 'contracts/asset-manager/asset-manager.clar'
clarity_version = 2
epoch = 2.4

[contracts.asset-manager-messages]
path = 'contracts/asset-manager/messages.clar'
clarity_version = 2
epoch = 2.4

[contracts.bnusd]
path = 'contracts/bnusd/bnusd.clar'
clarity_version = 2
epoch = 2.4

[contracts.bnusd-messages]
path = 'contracts/bnusd/messages.clar'
clarity_version = 2
epoch = 2.4

[contracts.call-service-receiver-trait]
path = 'lib/xcall/call-service-receiver-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.call-service-trait]
path = 'lib/xcall/call-service-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.rlp-decode]
path = 'lib/rlp/rlp-decode.clar'
clarity_version = 2
epoch = 2.4

[contracts.rlp-encode]
path = 'lib/rlp/rlp-encode.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc]
path = 'contracts/mocks/sbtc.clar'
clarity_version = 2
epoch = 2.4

[contracts.sip-010-trait]
path = 'lib/sips/sip-010-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.token]
path = 'contracts/mocks/token.clar'
clarity_version = 2
epoch = 2.4

[contracts.xcall-manager]
path = 'contracts/xcall-manager/xcall-manager.clar'
clarity_version = 2
epoch = 2.4

[contracts.xcall-manager-messages]
path = 'contracts/xcall-manager/messages.clar'
clarity_version = 2
epoch = 2.4

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
